// packages/reviewing-agent/src/types.ts

export interface ReviewTaskPayload {
  /** What to review — typically the code generated by an upstream code_task. */
  request: string
  /**
   * Optional: the code under review (in-band). If omitted, the request
   * is expected to point at the code via free-form description (e.g.,
   * "the code in the prior task's result").
   */
  code?: string
  /** Optional language hint. */
  language?: string
  /** Model name override. */
  model?: string
}

export type ReviewVerdict = 'approve' | 'request_changes' | 'reject'

export interface ReviewTaskResult {
  verdict: ReviewVerdict
  /** Human-readable summary of the review. */
  summary: string
  /** Specific issues found, if any. Free-form structured by the model. */
  issues?: string[]
  modelUsed: string
  finishReason: 'stop' | 'length' | 'content_filter' | 'tool_calls' | 'error'
  usage?: {
    promptTokens: number
    completionTokens: number
    totalTokens: number
  }
}

export const REVIEW_TASK_KIND = 'review_task' as const
export type ReviewTaskKind = typeof REVIEW_TASK_KIND
